Disable TXchecksum/SG/TSO to work around Realtek bugs
xcp-ng-rpms/r8125-module pull request #5
Opened 2024-02-02 17:05 UTC by andrew64k

Disable TXchecksum/SG/TSO to work around Realtek bugs. Some cards have this disabled by default already, some don't.
This disables the performance features by default for all. Can be re-enabled using ```ethtool -K eth0 tx on tso on sg on```
Realtek does not issue release notes or respond to emails...

Fixes Windows Server 2022 guest network data errors.
Issue reported by [glenlewis09](https://xcp-ng.org/forum/user/glenlewis09) on [forum post](https://xcp-ng.org/forum/topic/8289)

2024-02-15 17:25 UTC, stormi commented
Hi and sorry for the delay. There's an unnecessary merge commit in this PR. Could you rebase?

2024-02-21 17:14 UTC, stormi requested changes
Rebase needed so that the PR contains a single, non-merge, commit.

2024-08-09 09:53 UTC, stormi commented
Ping @andrew64k

2024-12-23 09:44 UTC, andrew64k commented
git updated

2024-12-23 09:55 UTC, andrew64k commented
As this driver works with the RTL8126 (minimally tested, not officially supported), it would be good to include the 8126 firmware. For some unknown reason, Realtek has now split the 8125/8126 driver into two different driver sources.

There are also RTL8125 firmware additions.

Pull the firmware files from the official [linux-firmware](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtl_nic/).
Not all of the files are currently used, but a future driver update may need more of them.
```
rtl8125a-3.fw
rtl8125b-1.fw
rtl8125b-2.fw
rtl8125bp-2.fw
rtl8125d-1.fw
rtl8125d-2.fw
rtl8126a-2.fw
rtl8126a-3.fw
```

2025-02-12 18:29 UTC, stormi commented
I'll create a task for the firmware update :+1:

2025-02-14 09:47 UTC, tescande approved these changes
LGTM

2025-02-14 09:49 UTC, stormi approved these changes

2025-02-14 15:47 UTC, Nambrok approved these changes

2025-02-14 16:57 UTC, merged

2025-02-14 16:57 UTC, stormi commented
Koji build to http://koji.xcp-ng.org/taskinfo?taskID=76720